manifest:
  version: "1.0"
  defaults:
    remote: ncs
    revision: main

  self:
    path: west-manifest

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      repo-path: sdk-nrf
      revision: v3.2.4
      import: true
